### ISSUE TITLE
Falta fichero LICENSE

### ISSUE THREAD

**Issue by mercuriete** [Dynam1co/Python_Telegram_Bot#6]
El fichero LICENSE no está en el repositorio.

Puedes añadir el fichero leyendo esta documentación.
https://help.github.com/es/github/creating-cloning-and-archiving-repositories/licensing-a-repository

Me gustaría contribuir al proyecto pero no se que licencia tiene.
Me gustaría que tuviera licencia MIT como la mayoría de proyectos opensource.

Muchas gracias de antemano.

**Comment by Dynam1co** [comment]
Hola, muchas gracias por la recomendación. Ya hemos añadido el archivo de licencia, le hemos puesto GPL, por lo que puedes contribuir libremente.

Un saludo.
